// Mock data for the 数字员工 prototype.
// Avatars are 1-2 char initials rendered as colored chips (no real images).
window.__DATA__ = (function () {
  const employees = [
    {
      id: "zhaopin-li",
      name: "招聘小慧 · 李工",
      initial: "李",
      avatarTone: "indigo",
      role: "部门分身",
      tag: "HR",
      status: "live",            // live | evaluating | humanEval | pending
      kind: "分身",
      desc: "我的招聘助手，记得我经常招后端 / 算法两类岗位。",
      lastUpdate: "今天 14:08",
      lastActive: "12 分钟前",
      copies: 0,
      tasks: 42,
      im: { feishu: "connected", dingtalk: "connected", wecom: "unset" },
    },
    {
      id: "shichang-xiaotu",
      name: "市场小图 · 我的版",
      initial: "市",
      avatarTone: "green",
      role: "部门分身",
      tag: "运营",
      status: "humanEval",
      kind: "分身",
      desc: "整理周度市场动态，目前正在由我亲自评审输出风格。",
      lastUpdate: "今天 09:15",
      copies: 0,
      tasks: 6,
      im: { feishu: "unset", dingtalk: "unset", wecom: "unset" },
    },
    {
      id: "zhaopin-offer",
      name: "招聘小慧 · 我的 Offer 版",
      initial: "Of",
      avatarTone: "violet",
      role: "私人定制",
      tag: "HR",
      status: "evaluating",
      kind: "私人定制",
      desc: "在部门分身基础上，定制了 offer 谈判话术与薪资测算逻辑。",
      lastUpdate: "今天 10:30",
      progress: 71,
      copies: 0,
      tasks: 8,
      im: { feishu: "unset", dingtalk: "unset", wecom: "unset" },
    },
    {
      id: "xingye-xiaoyan",
      name: "行业小研 · 李工",
      initial: "研",
      avatarTone: "green",
      role: "部门分身",
      tag: "情报",
      status: "live",
      kind: "分身",
      desc: "每周一早上把 AI Infra 赛道周报推送给我，站内对话也会保留追问历史。",
      lastUpdate: "昨天",
      lastActive: "今天 08:00",
      copies: 0,
      tasks: 19,
      im: { feishu: "unset", dingtalk: "unset", wecom: "connected" },
    },
    {
      id: "zhaopin-xiaozhao",
      name: "招聘小慧 · 校招专版",
      initial: "校",
      avatarTone: "violet",
      role: "私人定制",
      tag: "HR",
      status: "live",
      kind: "私人定制",
      desc: "为校招场景定制的招聘助手，掌握实习生评估、校园招招聘营延。",
      lastUpdate: "今天 11:42",
      lastActive: "30 分钟前",
      copies: 0,
      tasks: 14,
      im: { feishu: "connected", dingtalk: "unset", wecom: "unset" },
    },
    {
      id: "wenan-xiaoshu",
      name: "文案小书 · 李工",
      initial: "书",
      avatarTone: "amber",
      role: "部门分身",
      tag: "写作",
      status: "pending",
      kind: "分身",
      desc: "帮我把会议纪要整理成对外发布的文稿，需要审核三条更新。",
      lastUpdate: "3 天前",
      lastActive: "3 天前",
      copies: 0,
      tasks: 5,
      im: { feishu: "connected", dingtalk: "unset", wecom: "unset" },
    },
  ];

  // Conversation history — each employee has a persistent thread.
  // Roles: user | agent | system
  const conversations = {
    "zhaopin-li": [
      { role: "system", text: "本会话仅限「招聘小慧 · 李工」。历史会自动保留，不支持新建窗口。", time: "今天 09:12" },
      { role: "agent",  text: "早，李工。昨天后端 P6 的 3 份简历我已经按你过去的口味排过序了，第一份候选人在 2018-2022 有完整的搜索召回背景。要现在过一下吗？", time: "今天 09:13" },
      { role: "user",   text: "先把第一位的项目经历摘出来给我，重点看搜推。", time: "今天 09:14" },
      { role: "agent",  text: "好的。三段相关经历：\n1) 2019 @ 美图 · 搜索召回，从 ES 迁到向量召回，CTR +6.2%\n2) 2020 @ 某独角兽 · 推荐重排，引入 listwise loss\n3) 2022 @ 现公司 · 多路融合 + 端上重排\n要我拉出他每段的产出指标吗？", time: "今天 09:15" },
      { role: "user",   text: "拉一下，再顺便看下他过去面试反馈里的减分项。", time: "今天 09:15" },
      { role: "agent",  text: "减分项主要两条：① 沟通节奏偏快，需要面试官引导收敛；② 对业务指标的拆解不够细。要不要我把这两条放进面试官提醒里？", time: "今天 09:17" },
      { role: "user",   text: "放。另外帮我约下午 4 点的一面。", time: "今天 14:05" },
      { role: "agent",  text: "已发出邀约（飞书 + 钉钉同步），候选人 14:08 已确认。要我在面试前 15 分钟提醒你吗？", time: "今天 14:08" },
    ],
    "zhaopin-offer": [
      { role: "system", text: "本会话仅限「招聘小慧 · 我的 Offer 版」。当前 AI 评估进度 71%，部分能力尚未解锁。", time: "今天 10:30" },
      { role: "agent",  text: "李工，你上传的薪资带宽 2026Q2 已经载入。要不要我先跑一遍上周那位 P6 候选人的 offer 测算？", time: "今天 10:31" },
      { role: "user",   text: "跑一下，按竞品 +8% 的口径。", time: "今天 10:32" },
      { role: "agent",  text: "测算完成：\n· 现金部分：建议 base 56k × 16，浮动 ±2k\n· 期权：4 年归属，建议给到 1.8x 中位\n· 签字费：8w，分两年返还\n谈判优先级：base > 期权 > 签字费。要导出一份谈判脚本吗？", time: "今天 10:33" },
      { role: "user",   text: "先不要，等 AI 评估完整跑完再说。", time: "今天 10:34" },
    ],
    "zhaopin-xiaozhao": [
      { role: "system", text: "本会话仅限「招聘小慧 · 校招专版」。该员工是你为校招场景定制的版本。", time: "今天 11:00" },
      { role: "agent",  text: "李工，终面三期名单整理完了。名单上 28 位同学，按调带意愿度 + 笔试成绩已预排。Top 5 要我现在带过一下吗？", time: "今天 11:30" },
      { role: "user",   text: "先看 1、3 位，主要关注 ACM 背景。", time: "今天 11:35" },
      { role: "agent",  text: "好的：\n· 同学 1：ACM-ICPC 亚区赛金奖，本科期间 2 篇 SIGKDD\n· 同学 3：ACM区域赛银奖，毕设是分布式训练框架\n要不要我把他们两位推进「分布式系统」面试名单？", time: "今天 11:38" },
      { role: "user",   text: "推进去，顺便给他们一些实习生专属题。", time: "今天 11:40" },
      { role: "agent",  text: "已加入「实习生专属题」题库（3 道代码题 + 1 道场景题）。面试官邮件 12:00 发出。", time: "今天 11:42" },
    ],
    "xingye-xiaoyan": [
      { role: "system", text: "本会话仅限「行业小研 · 李工」。每周一 08:00 自动推送周报。", time: "周一 08:00" },
      { role: "agent",  text: "本周 AI Infra 赛道关键变化（3 条）：\n1) 国内推理框架开源生态多 2 家入场\n2) H20 替代方案的 PoC 在金融行业落地\n3) 端上小模型 4B 以下的产品化加速\n要看哪条的细节？", time: "周一 08:00" },
      { role: "user",   text: "第 2 条。重点看银行场景。", time: "周一 09:20" },
      { role: "agent",  text: "已展开。某股份制银行 2025Q4 启动的 PoC，结论：在风控离线推理上替代率 ~70%，时延可接受；在线交易场景仍依赖原方案。我把原始文档链接放在右上「资料」里了。", time: "周一 09:22" },
      { role: "user",   text: "好。帮我留意一下这家银行后续的公开招标。", time: "今天 08:00" },
      { role: "agent",  text: "已加入监控清单，下次出现公开招标 / 中标公告会第一时间发到这里。", time: "今天 08:00" },
    ],
    "wenan-xiaoshu": [
      { role: "system", text: "本会话仅限「文案小书 · 李工」。当前有 3 条更新待你审核。", time: "3 天前" },
      { role: "agent",  text: "上周三的产品评审纪要我整理成了三版文案：① 全员同步版；② 对外公关版；③ 客户邮件版。请按需审核。", time: "3 天前" },
      { role: "user",   text: "先看对外公关版，控制在 400 字以内。", time: "3 天前" },
      { role: "agent",  text: "已压缩到 386 字，重点保留了「自研推理栈、节省 32% 算力、Q3 全量」。要直接进入审核流程吗？", time: "3 天前" },
    ],
  };

  return { employees, conversations };
})();
